name: Test

on:
  push:
    branches:
      - master
      - alpha
      - beta
  pull_request:
    branches:
      - master
      - alpha
      - beta

jobs:
  main:
    name: Unit (Client and Server), E2E and Integration Test
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run build:check
      - run: npm run test:unit
      - run: npm run test:e2e
      - run: npm run test:client
      - run: npm run test:integration
  linux:
    name: "Node ${{ matrix.node }} on Linux: Server Unit and E2E Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run test:unit
      - run: npm run test:e2e
  windows:
    name: "Node ${{ matrix.node }} on Windows: Server Unit and Client Unit Test"
    runs-on: windows-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm ci
      - run: npm run test:unit
